// The agent-facing catalog. Slash menus are for humans; this list is what a
// command on /pi will do. `where: 'client'` runs in a connected browser.
export const CONTROLS = [
  { id: 'capture', where: 'client', args: { client: 'phone | desktop | all' }, summary: 'PNG of what that browser is showing' },
  { id: 'window-open', where: 'client', args: { kind: 'video | image | text | page', src: '/content/media/… or /antiburn.html', title: 'string?', windowId: 'string?' }, summary: 'spawn the same canvas window; in-app media/text, or a page such as antiburn' },
  { id: 'window-close', where: 'client', args: { windowId: 'string?' }, summary: 'close a spawned canvas window' },
  { id: 'hello', where: 'client', summary: 'tag this tab as phone or desktop' },
  { id: 'snapshot', where: 'server', summary: 'full GUI state' },
  { id: 'sessions', where: 'server', summary: 'list the session archive' },
  { id: 'live', where: 'server', summary: 'advertising terminals' },
  { id: 'attach', where: 'server', args: { pid: 'number' }, summary: 'watch a live terminal' },
  { id: 'detach', where: 'server', summary: 'stop watching' },
  { id: 'prompt', where: 'server', args: { text: 'string', behavior: 'steer?' }, summary: 'send a turn' },
  { id: 'abort', where: 'server', summary: 'stop the turn' },
  { id: 'new', where: 'server', summary: 'start a session' },
  { id: 'resume', where: 'server', args: { path: 'session file' }, summary: 'open an archived session' },
  { id: 'model', where: 'server', args: { provider: 'string', modelId: 'string' }, summary: 'switch model' },
  { id: 'models', where: 'server', summary: 'list models' },
  { id: 'name', where: 'server', args: { name: 'string' }, summary: 'name the session' },
  { id: 'reload', where: 'server', summary: 'reload skills and extensions' },
  { id: 'compact', where: 'server', args: { text: 'string?' }, summary: 'summarize older context' },
  { id: 'thinking', where: 'server', args: { level: 'string?' }, summary: 'get or set thinking level' },
  { id: 'session', where: 'server', summary: 'session id, file, tokens, cost' },
  { id: 'copy', where: 'server', summary: 'last assistant text' },
  { id: 'forks', where: 'server', summary: 'user turns you can fork from' },
  { id: 'fork', where: 'server', args: { entryId: 'string' }, summary: 'new session from a user turn' },
  { id: 'tree', where: 'server', args: { entryId: 'string' }, summary: 'jump to a turn in this file' },
  { id: 'settings', where: 'server', summary: 'Pi settings.json' },
  { id: 'dialog', where: 'server', summary: 'answer a permission dialog' },
];
